name: Integration Tests

on:
  workflow_call:

  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      db-test:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Set up Python & Poetry
        uses: EM51641/DDD_api_template/.github/actions/build_app@main

      - name: Execute Pytest
        run: poetry run python -m pytest --cov=app tests
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
