name: Typing

on: 
  workflow_call:

  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python & Poetry
        uses: EM51641/DDD_api_template/.github/actions/build_app@main

      - name: Execute mypy
        run:  poetry run mypy app